CREATE DATABASE DELDB;
USE DELDB;
CREATE TABLE EMPLOYEE
(
   EMPLOYEE_NAME VARCHAR (20),
   EMPLOYEE_ID VARCHAR (20),
   MARITIAL_STATUS VARCHAR (20)
);
INSERT INTO EMPLOYEE VALUES
(
   'Vishesh',
   '22576',
   'Married'
);
INSERT INTO EMPLOYEE VALUES
(
   'Supriya Shankar',
   '22577',
   'Married'
);
SELECT *
FROM
   EMPLOYEE;