USE DELDB;

CREATE TABLE EMPLOYEE1
(
   EMPLOYEE_NAME VARCHAR (20),
   FIRST_NAME VARCHAR (20),
   LAST_NAME VARCHAR (25),
   EMPLOYEE_ID VARCHAR (20),
   COMPANY VARCHAR (23),
   HIRE_DATE DATE,
   SALARY Decimal(8,2),
   MARITIAL_STATUS VARCHAR (20)
);